### ISSUE TITLE
Bad link for installing Anaconda

### ISSUE THREAD

**Issue by mtorpey** [St-Andrews-Carpentries/2024-06-17-standrews#1]
Instructions for installing Python include the link

<https://www.anaconda.com/products/individual#download-section>

but this now links to a page that asks you for your personal details with a tiny "Skip registration" link that's almost impossible to see.

A better link would be

<https://www.anaconda.com/download/success>

which actually, finally, lets users download the stuff.

I can't find where the installation instructions are stored.  Maybe this is an issue that should go in an upstream repo somewhere?

**Comment by olexandr-konovalov** [comment]
yes, sure - please submit an issue to https://github.com/carpentries/workshop-template

**Comment by mtorpey** [comment]
Great!  Made a PR: https://github.com/carpentries/workshop-template/pull/827
